# Konveyor AI Evaluation Configuration

# Models to evaluate
# Each model will be tested against all test cases
models:
  - name: "gpt-4-turbo"
    provider: "openai"  # Options: openai, anthropic, google
    api_key: "${OPENAI_API_KEY}"  # Use env var or set directly "sk-..."

    # temperature: Controls randomness (0.0-2.0)
    #   0.0 = Deterministic, consistent responses
    #   0.2 = Slightly varied (recommended for code)
    #   1.0 = Balanced creativity
    #   2.0 = Very creative/random
    temperature: 0.2

    # max_tokens: Maximum response length (~4 chars per token)
    #   2000 = ~8000 characters (~500-1000 lines)
    #   Increase for larger code fixes
    max_tokens: 2000

  - name: "claude-3-7-sonnet-latest"
    provider: "anthropic"
    api_key: "${ANTHROPIC_API_KEY}"
    temperature: 0.2  # Low temperature for consistent code fixes
    max_tokens: 2000

  # Google Gemini models
  # - name: "gemini-1.5-pro"
  #   provider: "google"
  #   api_key: "${GOOGLE_API_KEY}"
  #   temperature: 0.7
  #   max_tokens: 8192

  - name: "gpt-3.5-turbo"
    provider: "openai"
    api_key: "${OPENAI_API_KEY}"
    temperature: 0.2  # Low temperature for consistent code fixes
    max_tokens: 2000

# Evaluation dimensions (enable/disable)
evaluation_dimensions:
  functional_correctness:
    enabled: true
    compile_check: true
    static_analysis_rerun: true

  code_quality:
    enabled: true
    tools:
      - pylint
      - radon  # Cyclomatic complexity
      - black  # Style checking
    thresholds:
      max_complexity: 10
      min_pylint_score: 7.0

  security:
    enabled: true
    tools:
      - bandit  # Python security linter
    fail_on_high_severity: true

  efficiency:
    enabled: false  # Requires runtime execution
    timeout_seconds: 30
    memory_limit_mb: 512

  explainability:
    enabled: true
    require_comments: true
    use_llm_grader: true  # Use another LLM to grade explanations
    grader_model: "gpt-4-turbo"

  robustness:
    enabled: true
    prompt_variations: 3

  response_time:
    enabled: true
    trials: 3

# Static analysis configuration
static_analysis:
  # Path to Konveyor analyzer or custom rule engine
  analyzer_command: "konveyor-analyzer"
  rules_path: "benchmarks/rules/"

# Prompt templates (FALLBACK ONLY - prefer defining prompts in test case YAML files)
#
# NOTE: Prompts are now primarily defined in test case files for technology-specific guidance.
# When using --all-rulesets with --source/--target filters, appropriate prompts are auto-generated.
# This section only serves as a fallback for test cases without custom prompts.
#
# See benchmarks/test_cases/java-ee-quarkus-migration.yaml for examples.
prompts:
  default: |
    You are helping with code migration based on static analysis rules.

    {migration_guidance}

    Rule Violation:
    {rule_description}

    Konveyor Migration Guidance:
    {konveyor_message}

    Original Code:
    ```{language}
    {code_snippet}
    ```

    Context: {context}

    Please provide:
    1. The COMPLETE corrected code that resolves the violation (include ALL original code - classes, fields, methods, everything)
    2. A brief explanation of the changes made

    IMPORTANT:
    - Provide the ENTIRE class with ALL fields and methods, not just the parts you changed
    - Follow the migration target's best practices

    Format your response as:
    FIXED CODE:
    ```{language}
    [your complete fixed code here]
    ```

    EXPLANATION:
    [your explanation here]

  variations:
    - "Fix the following code to resolve the static analysis violation: {rule_description}\n\n{code_snippet}"
    - "The code below violates rule {rule_id}. Please correct it.\n\n{code_snippet}"

# Storage configuration
# Controls where evaluation results are stored
storage:
  # Storage backend: 'file', 'sqlite', or 'postgresql'
  type: "file"  # Default: file-based JSON storage

  # For file backend
  path: "results/"

  # For sqlite backend (optional - enables historical tracking)
  # type: "sqlite"
  # path: "konveyor_iq.db"

  # For postgresql backend (optional - for team/production use)
  # type: "postgresql"
  # connection_string: "${DATABASE_URL}"  # postgresql://user:password@localhost:5432/konveyor_iq

# Reporting
reporting:
  formats:
    - html
    - markdown
  output_dir: "results/"
  include_failure_examples: true
  max_failure_examples: 10

  # Write results to database (in addition to files)
  # Requires storage.type to be 'sqlite' or 'postgresql'
  write_to_database: false

# Execution
execution:
  parallel_requests: 5
  retry_on_failure: 2
  cache_responses: true
  cache_dir: ".cache/"
